services:
  redis:
    image: redis:7.4-alpine
    container_name: my_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3-management-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - "8080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  celery-worker:
    build: .
    command: celery --app src.celery_app.app worker --pool solo --loglevel=INFO
    depends_on:
      - rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672//"
      SMTP_HOST: "maildev"
      DATABASE_URL: "postgresql+asyncpg://postgres:postgres@host.docker.internal:5432/task_manager"

  celery-beat:
    build: .
    command: celery --app src.celery_app.app beat --loglevel=INFO
    depends_on:
      - rabbitmq
      - celery-worker
    env_file:
      - .env
    environment:
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@rabbitmq:5672//"

# ===== Сервис по добавлению пользователя к задаче ===

  task-assignment-db:
    image: postgres:16
    container_name: task_assigment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_assigment
    ports:
      - "5433:5432"
    volumes:
      - task-assigment-data:/var/lib/postgresql/data

  task-assignment-service:
    build: ./src/service/task_assigment_service
    container_name: task_assigment_service
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - task-assignment-db
    environment:
      DATABASE_URL_SQLALCHEMY: "postgresql+asyncpg://postgres:postgres@task-assignment-db:5432/task_assigment"
      RABBIT_AMQP: "amqp://guest:guest@rabbitmq:5672/"

# ===== Notification Service =====

  notification-service:
    build: ./src/service/notification_service
    container_name: notification_service
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - "8001:8001"
    environment:
      REDIS_URL: "redis://redis:6379/0"

# ===== VOLUMES =====

volumes:
  redis-data:
  rabbitmq-data:
  task-assigment-data: