"""add user_id to tag

Revision ID: 01466aad413a
Revises: 9e7c0e459e56
Create Date: 2026-02-11 17:49:40.258879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01466aad413a'
down_revision: Union[str, Sequence[str], None] = '9e7c0e459e56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_task_id'), 'document', ['task_id'], unique=False)
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("DELETE FROM tag WHERE user_id IS NULL")
    op.alter_column('tag', 'user_id', nullable=False)
    op.drop_constraint(op.f('tag_name_key'), 'tag', type_='unique')
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_task_user_id'), 'task', ['user_id'], unique=False)
    op.create_index(op.f('ix_tasktag_tag_id'), 'tasktag', ['tag_id'], unique=False)
    op.create_index(op.f('ix_tasktag_task_id'), 'tasktag', ['task_id'], unique=False)
    op.create_unique_constraint(None, 'tasktag', ['task_id', 'tag_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasktag', type_='unique')
    op.drop_index(op.f('ix_tasktag_task_id'), table_name='tasktag')
    op.drop_index(op.f('ix_tasktag_tag_id'), table_name='tasktag')
    op.drop_index(op.f('ix_task_user_id'), table_name='task')
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.create_unique_constraint(op.f('tag_name_key'), 'tag', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('tag', 'user_id')
    op.drop_index(op.f('ix_document_task_id'), table_name='document')
    # ### end Alembic commands ###
