"""add_user_id_to_task

Revision ID: 9e7c0e459e56
Revises: d7227b385958
Create Date: 2026-02-09 20:50:05.967417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7c0e459e56'
down_revision: Union[str, Sequence[str], None] = 'd7227b385958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('DELETE FROM document')
    op.execute('DELETE FROM tasktag')
    op.execute('DELETE FROM task')
    op.add_column(
        'task',
        sa.Column('user_id', sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        'fk_task_user_id',
        'task', 'user',
        ['user_id'], ['id'],
        ondelete='CASCADE'
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_task_user_id', 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    # ### end Alembic commands ###
