"""init

Revision ID: 07892ff4e302
Revises: 
Create Date: 2026-03-15 09:53:02.158322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07892ff4e302'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taskassigment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('task_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id')
    )
    op.create_index(op.f('ix_taskassigment_task_id'), 'taskassigment', ['task_id'], unique=False)
    op.create_index(op.f('ix_taskassigment_user_id'), 'taskassigment', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taskassigment_user_id'), table_name='taskassigment')
    op.drop_index(op.f('ix_taskassigment_task_id'), table_name='taskassigment')
    op.drop_table('taskassigment')
    # ### end Alembic commands ###
